# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.55.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "FlyveMDMInventory",
      clean: true,
      code_coverage: true
    )
  end

  desc "Run code coverage with xcov"
  lane :coverage do
    xcov(
      project: "FlyveMDMInventory.xcodeproj",
      scheme: "FlyveMDMInventory",
      output_directory: "coverage",
      json_report: true,
      only_project_targets: true
    )
  end

  after_all do |lane|
    telegram(
        url_horn: ENV["TELEGRAM_WEBHOOKS"],
        message: "Fastlane is OK"
    )
  end

  error do |lane, exception|
    telegram(
        url_horn: ENV["TELEGRAM_WEBHOOKS"],
        message: "`ERROR` Fastlane FAIL"
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
